# Generated by Django 5.2.6 on 2025-10-30 09:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], max_length=10)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('perceptual_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('integrity_status', models.CharField(choices=[('clean', 'Clean - No Edits Detected'), ('suspicious', 'Suspicious - Possible Edits'), ('modified', 'Modified - Edits Detected'), ('error', 'Error During Analysis')], default='clean', max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_files', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_exif', models.BooleanField(default=False)),
                ('exif_software', models.CharField(blank=True, max_length=255)),
                ('exif_datetime_original', models.CharField(blank=True, max_length=100)),
                ('exif_datetime_modified', models.CharField(blank=True, max_length=100)),
                ('exif_anomalies', models.TextField(blank=True, help_text='JSON or text describing anomalies')),
                ('pdf_creator', models.CharField(blank=True, max_length=255)),
                ('pdf_producer', models.CharField(blank=True, max_length=255)),
                ('pdf_creation_date', models.CharField(blank=True, max_length=100)),
                ('pdf_modification_date', models.CharField(blank=True, max_length=100)),
                ('pdf_page_count', models.IntegerField(blank=True, null=True)),
                ('pdf_anomalies', models.TextField(blank=True)),
                ('metadata_mismatch', models.BooleanField(default=False)),
                ('suspicious_software', models.BooleanField(default=False)),
                ('hash_collision', models.BooleanField(default=False)),
                ('detection_summary', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='0-100 confidence that file is unmodified', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_report', to='auditor.uploadedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['user', '-uploaded_at'], name='auditor_upl_user_id_290d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['integrity_status'], name='auditor_upl_integri_8df524_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['sha256_hash'], name='auditor_upl_sha256__9ed151_idx'),
        ),
    ]
