# Generated by Django 5.2.6 on 2025-12-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0002_uploadedfile_unique_file_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='sha256_hash',
            field=models.CharField(max_length=64),
        ),
    ]
